### ISSUE TITLE
this.frequencyData 遍历出来全部是零

### ISSUE THREAD

**Issue by Caraws** [ife2017/doubanfm#1]
请问用 crossOrigin = 'anonymous' 实现跨域的时候,你服务器端有做什么处理吗,因为我没有服务器 所以不知道怎么办了..

**Comment by qiuxiang** [comment]
不需要服务器的，audio 本来就是支持跨域的。

**Comment by Caraws** [comment]
但是如果不用的话 画不出来音频,播放也没有声音. 我把音乐单换成你的再用 crossOrigin = 'anonymous' 才能正常

**Comment by qiuxiang** [comment]
你的音频地址是什么？我试试

**Comment by Caraws** [comment]
```
http://m2.music.126.net/VGVtmHpkWLkEdAKUz2U0Qw==/18667508418127853.mp3
```
这种

**Comment by qiuxiang** [comment]
哦，是了，由 script 发起的请求都是受 CROS 限制的，也就是需要服务端响应的时候提供 Access-Control-Allow-Origin 响应头，而豆瓣电台的服务器端是有返回 Access-Control-Allow-Origin: *，所以可以跨域。

而 crossOrigin = 'anonymous' 是为了使用跨域数据。

**Comment by Caraws** [comment]
所以这里你用了 crossOrigin : ' anonymous' 其实只是为了用音频的数据是吗

**Comment by qiuxiang** [comment]
是的，关键是服务端要返回 Access-Control-Allow-Origin，关于 crossOrigin 属性你可以看这里 https://developer.mozilla.org/zh-CN/docs/Web/HTML/CORS_settings_attributes

我没有找到 audio 下 crossOrigin 的描述，但你可以参考 img 的 https://developer.mozilla.org/zh-CN/docs/Web/HTML/CORS_enabled_image

**Comment by Caraws** [comment]
恩恩~ 谢谢~
